from transformers import  AutoTokenizer

prompts=[
#      "A B C D E",
     'One day, as Tang Sanzang and his disciples traveled westward, they arrived at a barren valley. Unbeknownst to them, lurking in the shadows was the sinister White Bone Demon, who sought to devour the monk and gain his spiritual essence. Disguising herself as a village maiden carrying a basket of food, she approached the travelers with feigned kindness.\n"Great masters," she said sweetly, "I bring food for weary pilgrims. Please accept my humble offering."\nBut Sun Wukong, the ever-vigilant Monkey King, immediately sensed the demonic aura emanating from her. Without hesitation, he leaped forward and struck her with his golden cudgel. In a flash, the maiden’s body vanished, leaving only a wisp of ghostly smoke behind. Shocked, Tang Sanzang scolded him harshly.',
     'However, Sanzang was unconvinced and warned Wukong not to act so rashly again. Meanwhile, the White Bone Demon, having escaped death, was furious. Determined to succeed, she transformed herself into an elderly woman and once more approached the travelers, pretending to be the maiden’s grieving mother.\n"Oh, wandering monks, have you seen my daughter? She went to bring you food and never returned!"\n Again, Wukong saw through the deception and, with a mighty blow, struck down the old woman. Once more, she vanished into a trail of smoke. This time, Tang Sanzang grew furious. "Twice now, you have slain innocent people! If you act out of violence once more, I will banish you!"',
     'Yet the demon was persistent. She made a final attempt, this time appearing as an elderly man. Approaching them with sorrowful eyes, she wept, "Both my wife and daughter have gone missing since meeting you, kind travelers. Have you seen them?"\n Wukong, unwavering in his resolve, swung his staff once more, striking the demon’s true form. This time, she could no longer flee and was finally destroyed.However, Tang Sanzang, deceived by appearances, could no longer tolerate Wukong’s actions. He recited the Golden Circlet Spell, causing unbearable pain to the Monkey King’s head. Defeated and misunderstood, Wukong was ultimately dismissed from the journey.',
     "Sun Wukong, the Monkey King, was born from a magical stone and became the king of the monkeys. Seeking immortality and power, he trained under the Taoist master Subhuti, who taught him transformation techniques and the 72 Earthly Transformations. He also acquired the Somersault Cloud, allowing him to travel vast distances instantly.\n Armed with the Golden-Banded Staff (Ruyi Jingu Bang), which he took from the Dragon King of the Eastern Sea, Sun Wukong grew arrogant and defied celestial authority. In an attempt to pacify him, the Jade Emperor invited him to Heaven and gave him the humble post of Protector of the Horses. Realizing he was merely a stablekeeper, Sun Wukong rebelled, declaring himself The Great Sage Equal to Heaven.",
     "The Jade Emperor, wary of conflict, officially granted him the title but assigned him a meaningless duty overseeing the Peach Garden. When Sun Wukong discovered that he was excluded from the grand Peach Banquet, he became furious, devoured the divine peaches, stole the Elixir of Immortality from Laozi’s alchemy lab, and caused chaos in Heaven.\nHe defeated celestial armies sent to subdue him, including Nezha and the Four Heavenly Kings. Even Erlang Shen, one of the strongest warriors of Heaven, had to engage in a fierce battle with him. Eventually, the Buddha intervened, challenging Sun Wukong to escape from his palm. Overconfident, Sun Wukong somersaulted to what he believed was the edge of the universe, marking his presence on five pillars. However, he soon realized that these were merely Buddha’s fingers.",
     "中国乒乓球历史上涌现了许多著名的运动员，他们在国际赛场上取得了辉煌的成就。以下是一些著名的中国乒乓球运动员及其主要成就：容国团：中国乒乓球历史上的传奇人物，1959年在第25届世界乒乓球锦标赛上获得男子单打冠军，这是中国乒乓球历史上的第一个世界冠军。庄则栋：中国乒乓球的标志性人物之一，曾在1961年、1963年和1965年连续三届世界乒乓球锦标赛上获得男子单打冠军，成为中国乒乓球历史上首位“三连冠”选手。\n短道速滑世锦赛：中国选手刘少昂在男子1500米比赛中获得铜牌，但在5000米接力半决赛中腿部受伤，可能影响后续比赛1。\n上海黄浦半程马拉松：2025年3月30日，上海黄浦半程马拉松将正式开跑，起点设在外滩金牛广场，终点为世博黄浦体育园，参赛规模为8000人。赛事融合了轮滑和路跑元素，展现了上海的多元文化",
     "国足热身赛胜利：中国国家足球队在热身赛中以3-1战胜科威特，李磊和拜合拉木分别进球，为国足即将到来的世预赛增添了信心。接下来，国足将分别对阵沙特和澳大利亚.\nWTT重庆冠军赛：中国乒乓球选手王楚钦以3:0完胜瑞典选手莫雷加德，晋级男单四强。女单方面，孙颖莎、王曼昱、王艺迪和陈幸同包揽四强席位，展现了国乒的强大实力\n 贵阳市中考体育考试：2025年贵阳市中考体育考试将于4月7日开考，考试内容包括长跑、立定跳远等项目。贵阳市教育局强调考试的安全性和公平性，确保考试顺利进行",
     "Imagine a breathtaking fantasy landscape during the golden hour, where the sun is setting behind a range of majestic snow-capped mountains. The sky is painted in vibrant hues of orange, pink, and purple, with scattered clouds reflecting the warm sunlight. In the foreground, a crystal-clear river winds through a lush valley, its surface shimmering with golden light. On the riverbank, a small medieval village with stone cottages and thatched roofs is nestled among blooming cherry blossom trees, their petals gently falling into the water. A cobblestone path leads from the village to a grand, ancient castle perched on a hill, surrounded by dense, enchanted forests with glowing mushrooms and ethereal blue fireflies.",
     '森林里住着一只红色的小狐狸，它的皮毛像晚霞一样美丽，尾巴尖上还带着一点雪白。小狐狸最喜欢在夜晚爬到最高的松树上，数着天上的星星。可是最近，星星越来越少了\n"月亮婆婆，为什么星星都不见了呢？"小狐狸仰着头问。\n月亮婆婆叹了口气："因为人类城市的灯光太亮了，星星们都躲起来了。"\n小狐狸抖了抖耳朵，它决定要做点什么。它跑遍了整个森林，收集萤火虫的光芒、露珠的晶莹，还有月光织成的丝线。它用这些材料做了一盏小小的星星灯，挂在最高的松树上。',
     'Once upon a time, in a small village nestled between rolling green hills, there lived a humble tailor. He was a small man with nimble fingers and a quick wit. One fine morning, as he sat by his window sewing a vest, a swarm of flies buzzed around his jam sandwich.\nWith a swift motion, the tailor grabbed his cloth and swatted the flies. When he lifted the cloth, he counted seven dead flies lying on his sandwich. Amazed by his own strength, he decided to make a belt that read: "Seven with One Blow!""'
     'Proud of his new belt, the little tailor set out to seek his fortune. His first encounter was with a giant who laughed at the small man\'s belt. "Seven with one blow? You must mean flies!" the giant roared.\nBut the tailor was clever. He challenged the giant to a contest of strength. When the giant squeezed water from a stone, the tailor squeezed "milk" from cheese. When the giant threw a rock high into the air, the tailor released a bird that flew out of sight. The giant, thoroughly impressed, invited the tailor to meet his brothers.',
     "That night, while the giants slept, the clever tailor replaced their crowns with simple caps. In the morning, when the giants saw their changed headwear, they believed the little man had magical powers and fled in fear.\nContinuing his journey, the tailor came across a king who offered his daughter's hand in marriage to anyone who could rid the kingdom of two troublesome giants and a dangerous unicorn. The little tailor, with his quick thinking, tricked the giants into fighting each other and captured the unicorn by standing before a tree, causing it to charge and get its horn stuck in the trunk.\nThe king, true to his word, gave the tailor his daughter's hand in marriage. But the princess, proud and haughty, looked down upon her humble husband. One night, she overheard her husband talking in his sleep, revealing his true identity as a mere tailor.",
     "宙斯（Zeus）是古希腊神话中的众神之王，掌管天空、雷电和正义。他的故事充满了权力斗争、智慧与爱情，以下是关于宙斯的主要传说：\n1. 宙斯的诞生与童年:\n宙斯是克洛诺斯（Cronus）和瑞亚（Rhea）最小的儿子。克洛诺斯曾因预言自己会被子女推翻，于是吞下了所有孩子。瑞亚为了保护宙斯，用一块石头代替婴儿交给克洛诺斯，并将宙斯藏在克里特岛的山洞中，由仙女阿玛尔忒亚（Amalthea）抚养长大"
     "World War II, spanning from 1939 to 1945, was the most extensive and deadliest conflict in human history, involving over 100 million people from more than 30 countries. It reshaped the global political landscape and left an indelible mark on the 20th century.\nOrigins of the War:\nThe seeds of World War II were sown in the aftermath of World War I. The Treaty of Versailles, which ended the first global conflict, imposed harsh reparations and territorial losses on Germany, fostering resentment and economic instability. The rise of Adolf Hitler and the Nazi Party in the 1930s, with their ideology of Aryan supremacy and territorial expansion, further destabilized Europe.",
     "Key Events:\n1.Invasion of Poland (1939): Germany's invasion of Poland on September 1, 1939, prompted Britain and France to declare war, marking the official start of World War II.\n2.Battle of Britain (1940): The German Luftwaffe's sustained bombing campaign against Britain was met with fierce resistance by the Royal Air Force, preventing a German invasion.\n3.Operation Barbarossa (1941): Germany's invasion of the Soviet Union opened the Eastern Front, the largest and bloodiest theater of the war.\n4.Pearl Harbor (1941): Japan's surprise attack on the U.S. naval base at Pearl Harbor on December 7, 1941, brought the United States into the war.",
     "请深入分析 Transformer 模型中的自注意力（Self-Attention）机制，重点讨论其计算复杂度以及在大规模模型（如 GPT-4、Mixtral）上的优化策略。请结合 FlashAttention、MoE（Mixture of Experts）等技术，探讨如何降低计算成本和提高推理速度。",
     "“在云原生架构下，大型语言模型（LLM）的推理任务如何进行资源分配优化？请从容器化、分布式推理、负载均衡、缓存机制等方面展开讨论，并举例说明如何在 Kubernetes 集群中实现高效推理。”",
     "“请详细分析 CUDA 中的 warp 机制，并解释在不同计算任务（如矩阵乘法、图像处理、大规模数据并行计算）中的影响。请结合 __syncthreads() 的作用，说明如何优化线程块（Thread Block）的调度，以提高 GPU 计算效率。”",
     "Analyze the Self-Attention mechanism in Transformer models, focusing on its computational complexity and optimization strategies for large-scale models (e.g., GPT-4, Mixtral). Discuss how techniques like FlashAttention and MoE (Mixture of Experts) can reduce computational cost and improve inference efficiency."
     "Imagine you are the CEO of an AI startup developing an intelligent wearable device for Alzheimer’s patients. Design a market strategy including target customer profiling, marketing channels (social media, offline campaigns), pricing strategies, competitor analysis (e.g., Apple Watch, Huawei Smartwatch), and potential challenges in scaling the product.",
     "Analyze the key trends in the AI industry from 2024 to 2030, focusing on advancements in LLM inference acceleration, AI-generated content (AIGC), semiconductor technologies (e.g., NVIDIA H100, AMD Instinct MI300), and data security regulations (e.g., GDPR, AI Act). Predict the evolution of these technologies and their potential impact on different industries.",
     "“在大规模语言模型（LLM）推理过程中，如何优化 计算调度、张量分片（tensor parallelism）、KV 缓存管理 以提高吞吐量和减少延迟？请结合 vLLM、DeepSpeed、TensorRT 等优化框架，详细分析不同调度策略（如 greedy、first-fit、round-robin）对计算资源利用率的影响。此外，针对 MoE（Mixture of Experts）架构，请讨论如何高效管理专家选择和负载均衡，以避免计算资源的浪费。最后，请设计一组实验，在 不同 Batch Size 和 Sequence Length 下测试性能，并用数据可视化工具（如 Matplotlib、Seaborn）展示结果。”"
     """“自由意志的本质是什么？在人类认知领域，‘自由意志’通常被认为是个体自主决策的能力，但在物理学和神经科学中，许多人认为人的所有决策都是受 物理法则、神经活动、环境影响 所决定的，并非真正的‘自由’。那么，在人工智能系统中，我们是否能够构建出具备‘自由意志’的 AI？

第一部分：哲学分析 —— 从自由意志的两大流派（决定论 vs 非决定论）进行分析，探讨康德、萨特、丹尼特等哲学家的观点。
第二部分：神经科学与意识研究 —— 人类的‘自由意志’是否只是大脑的计算结果？如果是，AI 是否可以通过类似的计算获得自由意志？
第三部分：人工智能与决策模型 —— 目前 AI（如 Transformer-based LLM）做出的决策是否属于‘自主决定’？是否存在一种新的 AI 结构，可以具备比当前 LLM 更高层次的决策自由度？
第四部分：伦理与社会影响 —— 假设 AI 具备自由意志，是否应该赋予其法律权利？这种‘自由意志 AI’将如何影响人类社会？”""",
"The library of South China University of Technology was established in 1952, with the Foreign Textbooks Center directly under the State Ministry of Education and the Novelty Search Workstation at the ministerial level authorized by the State Ministry of Education, is among one of the largest libraries of the key polytechnic universities. The library of SCUT currently consists of the North Campus Library, the Branch Library of Chemical Machinery on the north campus and the South Campus Library, with a total floor space of 67,169 m2. The North Campus Library is situated on the left side of the main gate of the campus, with a total floor space of 24,269 m2, with 13 administrating departments including Curator's Office, Administrative Office, Acquisition Department, Cataloguing Department, Circulation Department, Reading Department, Periodical Department, Information Consultation Department, Electronic Document Department, Systems and Technology Department, North Campus Branch Library, Foreign Textbooks Center, Chinese Graphic Information Center, etc. The Branch Library of Chemical Machinery is located in the teaching building of the School of Mechanical and Automotive Engineering on the north campus with a total floor space of 600 m2 and two service departments, namely, Circulation Department and Reading Department. The South Campus Library, lying in the Guangzhou University Town, has a total floor space of 42,300 m2 and 5 departments including Administrative Office,"


]

if __name__=="__main__":
    tokenizer = AutoTokenizer.from_pretrained("/root/llm-resource/Models/Qwen1.5-MoE-A2.7B-Chat")
    input_ids = tokenizer(prompts)['input_ids']
    for ids in input_ids:
        print(len(ids))